### ISSUE TITLE
Running tom locally dies when trying to read from missing directory

### ISSUE THREAD

**Issue by jjatria** [melezhik/tomtit#3]
Running `tom` locally dies with the following error:
```
$ tom test
Failed to copy '/home/user/repo/api/v1/index' to '/home/user/sparrow6/index': Failed to copy file: no such file or directory
  in method get-resource at /home/user/.rakubrew/versions/moar-2022.06/install/share/perl6/site/sources/FBA5C2EEFF3791CAA61A1A30DE59E
```
This is apparently because the `S6_REPO` environment variable is not set, so it tries to read plugins from a local `~/repo`, which doesn't exist.

This directory (`~/repo`) does not sound like a very good default value, since there's nothing that connects it to Tomtit (or Sparrow, or anything related). But regardless of what that directory is, it might be a good idea to ignore it if it doesn't exist, rather than die.

**Comment by melezhik** [comment]
We can't ignore this. Tomtit requires that Sparrow plugins repository exists (as Tomtit scenarios _might_ use Sparrow plugins), even though a Tomtit users are not going to use Sparrow plugins ( only local tasks ), Tomtit needs to know where to fetch Sparrow repo index from. It might sound  as a limitation for only local tasks cases, however it makes it sure, that _if_ a user starts using Sparrow plugins in their scenarios this will work smoothly ...

With that being said Sparrow repositories are either set as local file repository or http repository, the  default is local file repository (`~/repo`). See more details on that [here](https://github.com/melezhik/Sparrow6/blob/master/documentation/repository.md)

We have a  few options here:

* Let Tomtit works in "offline" mode (by, say setting explicit cli option `--offline` ? ) where no Sparrow plugins repository is set, and this will work well for local tasks only cases. This will require some work to implement though and has a limitation of not supporting usage of Sparrow plugins ...

* Change default to https://sparrowhub.io/repo . This will satisfy most cases, but has a limitation of requiring network connectivity for Tomtit to work 

* _Legit_ fix for this error is to create _empty_ Sparrow repository:

```bash
s6 --repo-init
``` 
In this case you have local file repository, which you could populate with plugins in the future when you need ones ... So that Tomty will work in both local tasks only  mode and repo plugins mode .

What do you think?

**Comment by melezhik** [comment]
@jjatria can we close this one ?

**Comment by jjatria** [comment]
Looks like it! It doesn't die now at least :)

**Comment by melezhik** [comment]
correction - command should be `s6 --repo-init ~/repo`
